### ISSUE TITLE
Unable to log in after adding the sample content

### ISSUE THREAD

**Issue by Kodiack** [datagovuk/dgu-vagrant-puppet#106]
I'm able to log into Drupal using admin/admin after using Drush to install the site from /var/www/drupal/dgu, but once I copy over some of the nice sample content from dgud7_default_db.sql.gz, I'm entirely unable to log in at all and can only gain access again by reinstalling the base dgu site.

Is this intentional? The README.md may be a bit misleading since it says "You can now log-in with this user" immediately after the area where the sample content can be added.

**Comment by davidread** [comment]
@ratajczak is this something you're able to check?

**Comment by ratajczak** [comment]
@Kodiack, please execute 'drush uli' in your Drupal root to get one time log in link which allows you to log in and change the password.
I'm going to update README.md and suggest this way because Drupal passwords are salted (with $drupal_hash_salt variable in settings.php), this is a security measure to avoid breaking the password using rainbow tables when a database is stolen.
That means that these credentials (admin/admin) work only with hash salt from this Drupal instance where this user account was created.

**Comment by Kodiack** [comment]
That works well! It's good to know that the salted passwords are unique to a configuration. That wasn't always the case, and I don't think I'd have been experienced enough to find that out without a lot more research. :)

http://randyfay.com/content/resetting-drupal-passwords-drupal-7-drush-or-without

Things are looking quite good overall so far! I really appreciate how active you guys are in maintaining this.
