### ISSUE TITLE
About system requirements

### ISSUE THREAD

**Issue by heinlja** [datagovuk/dgu-vagrant-puppet#63]
The README of dgu-vagrant-puppet TOGO states the following system requirements:
 - 24GB RAM
 - 8 cores

Are these really necessary? I mean is the suggested minimum or does apply for some heavy user load only? Would 4 cores and 16GB of RAM do just as well?

**Comment by noels** [comment]
Those sound like a very bad guess to me. What you specified is possibly overkill.

**Comment by heinlja** [comment]
Ok, I'm asking because we're running a portal based on data.gov.uk, and experienced some memory problems, but really no details known yet. So I just wanted to check for starters, if one should really use the resources suggested in README.

Closing the ticket for now.

**Comment by davidread** [comment]
This config is just what we bought for our public server - something beefy so that we don't have to worry too much. I'm afraid we've not done anything to gauge whether it could be reduced.

On our developer machines we use 8GB VMs which works fine, but clearly that is not loaded like a public server.

**Comment by CarlQLange** [comment]
Just chiming in here - running this on a t1.micro on AWS, even just for personal testing, is an exercise in patience. You definitely need something quite a bit less... modest... for production machines
